@startuml  analysis1.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User -> Browser : initiates the exportation of a worksheet
Browser ->> Browser : asks for the settings
User -> Browser : enters the information
Browser -> Server : exportToPDF()
Browser -> Browser : download file

@enduml