@startuml  design1.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
boundary ExtensionsManagerView
control ExtensionsManagerPresenter
control ExtensionsServices
control ExtensionsManagerController
control WorkbookDescriptionService
entity WorkbookDescriptionRepository
database Database

box "NSheets Client"
participant HomeView
participant HomePresenter
end box

box "Shared"
participant WorkbookServices
participant ListWorkbookDescriptionController
participant WorkbookDescriptionService
participant WorkbookDescriptionRepository
end box

box "Database"
participant Database
end box

User -> HomePresenter : onReveal() / navigate to page
HomePresenter ->> WorkbookServices : getWorkbooks()
WorkbookServices -> ListWorkbookDescriptionController : listWorkbookDescriptions()
ListWorkbookDescriptionController -> WorkbookDescriptionService : allWorkbookDescriptions()
WorkbookDescriptionService -> WorkbookDescriptionRepository : findAll()
WorkbookDescriptionRepository -> Database : fetch
WorkbookServices ->> HomePresenter : onSuccess()
HomePresenter -> HomeView : setContents()

@enduml
