@startuml  design2.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
boundary CalendarView
control CalendarPresenter
control EditEventController
entity EventRepository
entity Event
database Database

box "NSheets Client"
participant CalendarView
participant CalendarPresenter
end box

box "Server"
participant EditEventController
participant Event
participant EventRepository
end box

box "Database"
participant Database
end box

User -> CalendarPresenter : selects event to edit
CalendarPresenter --> EditEventController : create()
CalendarPresenter -> EditEventController : selectEventToEdit()
EditEventController --> EventRepository : create()
EditEventController -> EventRepository : findById(Long id)
EventRepository  -> Database : fetch
CalendarView --> User : Show event and the user makes alterations
CalendarPresenter -> EditEventController : saveAlterations()
EditEventController --> Event : makeAlterations()
EditEventController -> EventRepository : save(Event e)
EventRepository  -> Database : save
EditEventController ->> CalendarPresenter : onSuccess()
CalendarPresenter -> CalendarView : setContents()
CalendarView --> User: Shows success

@enduml
