@startuml  us.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

User -> (US03: Display Events)
User -> (US02: Remove Event)
User -> (US02: Edit Event)
User -> (US01: Create Event)


@enduml