@startuml
skinparam handwritten false
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User->System: opens the settings and selects the CSV tab
System-->User: shows the csv tab
User->System: chooses the type of delimiter that he wants in the CSV file
System-->User: confirms his option
User->System: selects export to csv button in the workbook page
System-->User: asks what he wants to export (workbook, a spreadsheet of the workbook or part of a spreadsheet to a CSV file)
User->System: chooses one of the options
System-->User: confirms the option and crates a CSV file

Browser ->> Server : getInfo()

database Database

Server -> Database : fetch

Server -->> Browser : return

Browser -> Browser : display

Browser --> User : informs success of the operation
@enduml
