@startuml
actor Actor
  participant "WorkbookView" as WV
  

  Actor -> WV : starts pressing the colapsible bar and pressing the italic button
  WV -> WV : activecell= getActiveCell()
  WV -> CellStyleExtension : new()
  WV -> CellStyleExtension : setfStyle(Italic)
  WV -> WV : doStyleExt(ITALIC)
  WV -> Actor : Italic style applied to the cell
@enduml