@startuml  analysis.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User

User -> Browser : navigate to page
Browser ->> Server : getWorkbooks()
Browser -->>Server : launchFormEditor()
Server -->>Browser : existsForm()
Browser -->>Server : editForm()
Browser -->>Server : previewForm()
Browser -->>Browser : display
Browser -->>Server : SaveForm()

database Database

Server -> Database : fetch

Server -->> Browser : return

Browser -> Browser : display

@enduml
