@startuml  design1.png
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User
control WorkbookPresenter
control FormEditorWindow
control FormWindow
control Form
control FormEditorController
control Workbook

box "NSheets Client"
participant WorkbookPresenter
participant FormEditorWindow
participant FormWindow
end box

box "Server"
participant WorkbookServices
participant FormEditorController
participant Workbook
participant Form
end box



User -> WorkbookPresenter : onReveal() / navigate to page
WorkbookPresenter ->> WorkbookServices : getCurrentWorkbook()
User -> WorkbookPresenter : editForm() / Open a Window Editor
WorkbookPresenter -> FormEditorWindow : open(currentWorkBook);
FormEditorWindow -> FormEditorController : existsForm(currentWorkBook);
FormEditorWindow -> FormEditorWindow : display() or create()
FormEditorWindow -> FormWindow : preview()
FormEditorWindow -> FormEditorController : save(Map <String,String> rows);
FormEditorController -> Workbook : new(currentWorkbook, Map <String,String> rows);
Workbook -> Form : newForm(form) /update form;

@enduml
